### ISSUE TITLE
Function similar to mkList, that returns manifests like buildHelmChart

### ISSUE THREAD

**Issue by jakuzure** [farcaller/nix-kube-generators#2]
I played around with transforming a HelmChart as per the Nixcon talk (patchDeployment example) and it does work without any problems, but as far as I can tell, to transform it back into a YAML file, the mkList function needs to be used, which turns the manifests into a `kind: List` object. While this works and it's possible to apply it via kubectl, I would prefer to have the manifests separated by ---'s as they were after the buildHelmChart.

I tried around building a helper function for it, but couldn't get it working due to my limited Nix Lang abilities, so that's why I'm opening this issue, maybe you can help me out 😄

**Comment by farcaller** [comment]
There you go!

**Comment by jakuzure** [comment]
Works perfectly, thanks so much!
